include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

#
# Start custom overrides.
#

variables:
  # Disable default phpunit job in favor of the d9/10 variants below.
  SKIP_PHPUNIT: 1
  SKIP_COMPOSER: 1
  _PHPUNIT_EXTRA: --verbose

phpcs:
  # Set allow_failure to false so that the test fails for coding standards faults.
  allow_failure: false
  needs:
    - composer-d9
#  dependencies:
#    - "composer: [8.1, $CORE_MAJOR_DEVELOPMENT]"

composer-lint:
  needs:
    - composer-d9
#  dependencies:
#    - "composer: [8.1, $CORE_MAJOR_DEVELOPMENT]"

.composer-local:
  variables:
    SKIP_COMPOSER: 0

composer-d9:
  extends:
    - .composer-base
    - .composer-local
  variables:
    _TARGET_PHP: "7.4"
    _TARGET_CORE: "9.5.9"

# # Cant use needs with dependencies https://docs.gitlab.com/ee/ci/yaml/index.html#needs today.
# Bring back when https://gitlab.com/gitlab-org/gitlab/-/issues/254821 lands.
#composer:
#  parallel:
#    matrix:
#      - _TARGET_PHP: [ "7.4" ]
#        _TARGET_CORE: [ "9.5.9" ]
#      - _TARGET_PHP: [ "8.1" ]
#        _TARGET_CORE: [ "10.0.9 ]

.phpunit-local:
  variables:
    SKIP_PHPUNIT: 0
# An example of further matrix splitting of jobs.
#  parallel:
#    matrix:
#      # Run test groups in parallel for better dev velocity.
#      - _PHPUNIT_EXTRA: [ "--group devel", "--group devel_generate" ]

phpunit-d9:
  #dependencies:
    # This syntax comes from https://docs.gitlab.com/ee/ci/jobs/job_control.html#fetch-artifacts-from-a-parallelmatrix-job
    #- "composer: [7.4, $CORE_STABLE]"
  needs:
    - composer-d9
  variables:
    _TARGET_PHP: "7.4"
  extends:
    - .phpunit-base
    - .phpunit-local
